image: node:16-buster

stages:
  - test
  - build
  - deploy
  - release

cache:
  paths:
    - node_modules/

variables:
  REACT_APP_STATIC_PAGE_ONLY: "false"

# Test and build on PRs
test:
  stage: test
  script:
    - apt-get update && apt-get install -y libusb-1.0-0-dev libudev-dev
    - ln -s .env.${CI_COMMIT_BRANCH:dev} .env
    - yarn install
    - yarn lint
    - yarn test
    - yarn build
  only:
    - merge_requests
    - master
    - prod
    - dev
    - rococo
    - beta

build:
  stage: build
  variables:
    NODE_ENV: production
  script:
    - apt-get update && apt-get install -y libusb-1.0-0-dev libudev-dev
    - ln -s .env.${CI_COMMIT_BRANCH:dev} .env
    - yarn install
    - yarn build
  artifacts:
    expire_in: 1 day
    paths:
      - build
  only:
    - master
    - prod
    - dev
    - rococo
    - beta

build_container:
  stage: deploy

  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - |
      /kaniko/executor --context $CI_PROJECT_DIR \
        --dockerfile $CI_PROJECT_DIR/DockerfileProd \
        --destination $CI_REGISTRY_IMAGE:${CI_COMMIT_BRANCH}-$CI_COMMIT_SHORT_SHA \
        --destination $CI_REGISTRY_IMAGE:${CI_COMMIT_BRANCH}
  only:
    - master
    - prod
    - dev
    - rococo
    - beta

github_changelog:
  stage: release
  image: registry.gitlab.com/interlay/containers/github-publisher:master
  script:
    - gh auth status
    - git-chglog --output CHANGELOG.md $CI_COMMIT_TAG
    - gh release -R https://github.com/interlay/polkabtc-ui create $CI_COMMIT_TAG --title $CI_COMMIT_TAG -F CHANGELOG.md -d
  only:
    - tags
