# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

stages:
    - test
    - build
    - deploy

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
    paths:
        - node_modules/

variables:
    REACT_APP_STATIC_PAGE_ONLY: "false"

# Test and build on PRs
test:
  stage: test
  script:
    - apt-get update && apt-get install -y libusb-1.0-0-dev libudev-dev
    - ln -s .env.${CI_COMMIT_BRANCH:dev} .env
    - yarn install
    - yarn lint
    - yarn test --passWithNoTests
    - yarn build
  only:
    - merge_requests
    - master
    - prod
    - dev
    - rococo

build:
  stage: build
  variables:
    NODE_ENV: production
  script:
    - apt-get update && apt-get install -y libusb-1.0-0-dev libudev-dev
    - ln -s .env.${CI_COMMIT_BRANCH:dev} .env
    - yarn install
    - yarn build
  artifacts:
    expire_in: 1 day
    paths:
      - build
  only:
    - master
    - prod
    - dev
    - rococo

build_container:
  stage: deploy

  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - |
      /kaniko/executor --context $CI_PROJECT_DIR \
        --dockerfile $CI_PROJECT_DIR/DockerfileProd \
        --destination $CI_REGISTRY_IMAGE:${CI_COMMIT_BRANCH}-$CI_COMMIT_SHORT_SHA \
        --destination $CI_REGISTRY_IMAGE:${CI_COMMIT_BRANCH}
  only:
    - master
    - prod
    - dev
    - rococo
