name: yarn test

on: [push]

env:
  # ray test touch <
  REACT_APP_RELAY_CHAIN_NAME: polkadot
  REACT_APP_PARACHAIN_ID: 2032
  DOCKER_RELAY_CHAIN_CURRENCY: DOT
  # ray test touch >

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      if: github.event.pull_request.base.ref == 'master'
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install
    - run: yarn test
