name: yarn test

on: [push, pull_request_target]

env:
  REACT_APP_RELAY_CHAIN_NAME: polkadot
  REACT_APP_PARACHAIN_ID: 2032
  DOCKER_RELAY_CHAIN_CURRENCY: DOT
  REACT_APP_FEATURE_FLAG_LENDING: enabled

jobs:
  # MEMO: how to run a GitHub action locally
  # - Set up https://github.com/nektos/act
  # - Run this command: `act -j build --container-architecture linux/amd64` (where `build` is the job name and `--container-architecture` & `linux/amd64` are local computer specific parameters so may or may not need them) to locally run this `build` job
  # - `yarn` may not be available from a regular set-up of `act` then follow https://github.com/nektos/act/issues/280#issuecomment-817661786
  # - `--ignore-engines` may only be needed when locally running a GitHub action
  build:
    runs-on: [self-hosted, linux]

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      if: github.event.pull_request.base.ref == 'master'
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install --ignore-engines # RE: inspired by https://stackoverflow.com/a/57748163
    - run: yarn test
      env:
        NODE_OPTIONS: "--max-old-space-size=4096"
